/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./extension/*.html", "./extension/*.js"],
  theme: {
    extend: {
      colors: {
        "surface-container":         "#efeded",
        "surface-container-lowest":  "#ffffff",
        "surface-container-high":    "#e9e8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-container-low":     "#f5f3f3",
        "surface-bright":            "#fbf9f8",
        "surface":                   "#fbf9f8",
        "surface-dim":               "#dbdad9",
        "surface-variant":           "#e4e2e2",
        "background":                "#fbf9f8",
        "primary":                   "#705d00",
        "on-primary":                "#ffffff",
        "primary-container":         "#ffd700",
        "on-primary-container":      "#705e00",
        "primary-fixed-dim":         "#e9c400",
        "inverse-primary":           "#e9c400",
        "secondary":                 "#5f5e5e",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#e2dfde",
        "on-secondary-container":    "#636262",
        "tertiary":                  "#5d5f5f",
        "on-tertiary":               "#ffffff",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "on-surface":                "#1b1c1c",
        "on-background":             "#1b1c1c",
        "on-surface-variant":        "#4d4732",
        "inverse-surface":           "#303031",
        "inverse-on-surface":        "#f2f0f0",
        "outline":                   "#7e775f",
        "outline-variant":           "#d0c6ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      fontFamily: {
        sans:  ["Inter", "system-ui", "sans-serif"],
        title: ["Hanken Grotesk", "sans-serif"],
        mono:  ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
